### PR TITLE
Merge from upstream

### PR DESCRIPTION
**Pull request by MBeijer**

### CODE REVIEW

**Review by capehill — APPROVED** [review]

**Review by capehill — APPROVED** [review]

**Review by capehill — APPROVED** [review]

**Review by capehill — APPROVED** [review]

**Comment by MBeijer** [comment]
So, yeah, this is why I'd like us to move the sdl2-amigaos4 coding to this repo. Notifications about updates and fairly easy to pull the changes and bugfixes straight to the repo and less manual labor

**Comment by capehill** [comment]
@MBeijer not sure how to reply here, but yeah, I agree. After SDL 2.0.7 "final" is out, I will probably start using this repo.

**Comment by MBeijer** [comment]
@capehill Meanwhile, I've set up on my own repo so I can easily merge in new changes from the sdl2-amigaos4 repo master branch over to this one. =)

**Comment by MBeijer** [comment]
@capehill I suggest joining up in our AmigaPorts Slack: https://join.slack.com/t/amigaports/shared_invite/enQtMzE2NjE1MDg0OTkzLTYyYmRmZjliMTJhMGExZDUxMmFhZmIwMzA4NWNkZDIzMzcxMzE4OWFhY2UyMDZhODAzNDllMTU1NWFmNTdiZDU

It'll be easier to discuss things in realtime and don't mess upp issues and pull requests like this.

I've set it up to post all updates from this, sdl2-amigaos4 and libSDL12 in there as well.

Either you just use it in your browser or download the application =)

I understand if you don't feel like doing it, but it sure would help organize everything.

**Pull request merged**
